development:
  player: round_robin
  storage: memory

test:
  player: round_robin
  storage: memcache

production:
  player: epsilon_greedy
  player_config:
    epsilon: 0.1
  storage: redis
  storage_config:
    host: localhost
    port: 6379
