require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ArticleRatingsController do

  # This should return the minimal set of attributes required to create a valid
  # ArticleRating. As you add validations to ArticleRating, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "article_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ArticleRatingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all article_ratings as @article_ratings" do
      article_rating = ArticleRating.create! valid_attributes
      get :index, {}, valid_session
      assigns(:article_ratings).should eq([article_rating])
    end
  end

  describe "GET show" do
    it "assigns the requested article_rating as @article_rating" do
      article_rating = ArticleRating.create! valid_attributes
      get :show, {:id => article_rating.to_param}, valid_session
      assigns(:article_rating).should eq(article_rating)
    end
  end

  describe "GET new" do
    it "assigns a new article_rating as @article_rating" do
      get :new, {}, valid_session
      assigns(:article_rating).should be_a_new(ArticleRating)
    end
  end

  describe "GET edit" do
    it "assigns the requested article_rating as @article_rating" do
      article_rating = ArticleRating.create! valid_attributes
      get :edit, {:id => article_rating.to_param}, valid_session
      assigns(:article_rating).should eq(article_rating)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ArticleRating" do
        expect {
          post :create, {:article_rating => valid_attributes}, valid_session
        }.to change(ArticleRating, :count).by(1)
      end

      it "assigns a newly created article_rating as @article_rating" do
        post :create, {:article_rating => valid_attributes}, valid_session
        assigns(:article_rating).should be_a(ArticleRating)
        assigns(:article_rating).should be_persisted
      end

      it "redirects to the created article_rating" do
        post :create, {:article_rating => valid_attributes}, valid_session
        response.should redirect_to(ArticleRating.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved article_rating as @article_rating" do
        # Trigger the behavior that occurs when invalid params are submitted
        ArticleRating.any_instance.stub(:save).and_return(false)
        post :create, {:article_rating => { "article_id" => "invalid value" }}, valid_session
        assigns(:article_rating).should be_a_new(ArticleRating)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ArticleRating.any_instance.stub(:save).and_return(false)
        post :create, {:article_rating => { "article_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested article_rating" do
        article_rating = ArticleRating.create! valid_attributes
        # Assuming there are no other article_ratings in the database, this
        # specifies that the ArticleRating created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ArticleRating.any_instance.should_receive(:update).with({ "article_id" => "1" })
        put :update, {:id => article_rating.to_param, :article_rating => { "article_id" => "1" }}, valid_session
      end

      it "assigns the requested article_rating as @article_rating" do
        article_rating = ArticleRating.create! valid_attributes
        put :update, {:id => article_rating.to_param, :article_rating => valid_attributes}, valid_session
        assigns(:article_rating).should eq(article_rating)
      end

      it "redirects to the article_rating" do
        article_rating = ArticleRating.create! valid_attributes
        put :update, {:id => article_rating.to_param, :article_rating => valid_attributes}, valid_session
        response.should redirect_to(article_rating)
      end
    end

    describe "with invalid params" do
      it "assigns the article_rating as @article_rating" do
        article_rating = ArticleRating.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ArticleRating.any_instance.stub(:save).and_return(false)
        put :update, {:id => article_rating.to_param, :article_rating => { "article_id" => "invalid value" }}, valid_session
        assigns(:article_rating).should eq(article_rating)
      end

      it "re-renders the 'edit' template" do
        article_rating = ArticleRating.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ArticleRating.any_instance.stub(:save).and_return(false)
        put :update, {:id => article_rating.to_param, :article_rating => { "article_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested article_rating" do
      article_rating = ArticleRating.create! valid_attributes
      expect {
        delete :destroy, {:id => article_rating.to_param}, valid_session
      }.to change(ArticleRating, :count).by(-1)
    end

    it "redirects to the article_ratings list" do
      article_rating = ArticleRating.create! valid_attributes
      delete :destroy, {:id => article_rating.to_param}, valid_session
      response.should redirect_to(article_ratings_url)
    end
  end

end
